# Config from UnknownCommandMessageEdit
# Made by JonaHD345 (http://github.com/JonaHD345)
# Support, bugs & ideas: discord: jonahd345 or contact@jonahd345.de
# You can use '&' Colorcodes!
# With %Command% you can paste in the unknown command!

Config:
  Message: ''
