# Config from UnknownCommandMessageEdit
# Made by JonaHD345
# You can use '&' Colorcodes!
# With %Command% you can paste in the Unknown Command!

Config:
  Message: ''


# Bugs or Ideas please via Discord: JonaHD345#0827